import React, {Component, Fragment} from 'react'; 
import ReactDOM from 'react-dom'; 
import {HashRouter as Router, Route, Routes, Redirect} from 'react-router-dom'

import Dashboard from './layout/Dashboard';
// import Login from './auth/Login'
import Register from './auth/Register'
import Routing from './utilities/Routing'
import PrivateRoute from './auth/PrivateRoute'

import {Provider} from 'react-redux' // connects the redux stuff to React app
import store from '../store'

class App extends Component {
    render(){
        return (
            <Provider store={store}>
                <Router>
                    <Fragment>
                        <Dashboard />
                    </Fragment> 
                </Router>
            </Provider>
        )
    }
}

ReactDOM.render(<App />, document.getElementById('app')); 
// Insert app in an element with id 'app'

// The apparently "perfect" size of the navbar is the result of 
// the media queries generated by nabar class

// <PrivateRoute exact path={"/frontend"} component={Dashboard}/> 
//  <Route exact path={"/login"} component={Login} />
//                         <Routes>
// <Route path="*" element={<Routing />} />
// </Routes>