# Generated by Django 4.1.2 on 2023-01-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_date_joined_account_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/default/default.jpg', null=True, upload_to='profile/account/'),
        ),
    ]
