export const GET_RECENT_ADDITIONS = "GET_RECENT_ADDITIONS"; 
export const GET_CAROUSEL_DATA = "GET_CAROUSEL_DATA"; 
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"; 
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED"; 
export const AUTH_ERROR = "AUTH_ERROR"; 
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"; 
export const LOGOUT_FAIL = "LOGOUT_FAIL"; 
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES"; 
export const CREATE_MESSAGE = "CREATE_MESSAGE"; 
export const GET_OVERVIEW_DATA = "GET_OVERVIEW_DATA";
export const GET_OVERVIEW_GRAPH = "GET_OVERVIEW_GRAPH";
export const POST_SPENDING = "POST_SPENDING";

